server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.21.130:3306/ks_second_classroom?useUnicode=true&characterEncoding=utf8
    username: root
    password: 2459689935
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
mybatis-plus:
  type-aliases-package: com.einmeer.entity
logging:
  level:
    com.einmeer.mapper: debug
minio:
  username: admin
  password: 2459689935
  endpoint: http://192.168.21.130:9000